name: joke_fun_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^2.4.0
  # getX：https://pub-web.flutter-io.cn/packages/get/install
  get: ^4.6.5
  # 屏幕适配：https://pub-web.flutter-io.cn/packages/flutter_screenutil/install
  flutter_screenutil: ^5.8.4
  # 日志：https://pub-web.flutter-io.cn/packages/logger/install
  logger: ^1.4.0
  # 下拉刷新  https://pub-web.flutter-io.cn/packages/pull_to_refresh/install
  pull_to_refresh: ^2.0.0
  # 图片加载  https://pub-web.flutter-io.cn/packages/cached_network_image/install
  cached_network_image: ^3.2.3
  # retrofit https://pub-web.flutter-io.cn/packages/retrofit   flutter pub run build_runner build
  retrofit: ^4.0.1
  # dio https://pub-web.flutter-io.cn/packages/dio/install
  dio: ^5.3.1
  json_serializable: ^6.1.5
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  encrypt: ^5.0.1
  visibility_detector: ^0.4.0+2
  fijkplayer: ^0.11.0
  shared_preferences: ^2.2.0
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # retrofit
  retrofit_generator: '>=5.0.0 <6.0.0'
  # build_runner: '>=2.3.0 <4.0.0'
  build_runner: ^2.4.6

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/image/

